// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v5.28.2
// source: proto/order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "order";

export interface Empty {
}

export interface CreateOrderRequest {
  userId: number;
  productId: number;
  quantity: number;
  totalPrice: number;
}

export interface GetOrderRequest {
  id: number;
}

export interface UpdateOrderRequest {
  id: number;
  status: string;
  quantity: number;
  totalPrice: number;
}

export interface DeleteOrderRequest {
  id: number;
}

export interface Order {
  id: number;
  userId: number;
  productId: number;
  quantity: number;
  totalPrice: number;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface OrderList {
  orders: Order[];
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  createOrder(request: CreateOrderRequest): Observable<Order>;

  getOrders(request: Empty): Observable<OrderList>;

  getOrder(request: GetOrderRequest): Observable<Order>;

  updateOrder(request: UpdateOrderRequest): Observable<Order>;

  deleteOrder(request: DeleteOrderRequest): Observable<Empty>;
}

export interface OrderServiceController {
  createOrder(request: CreateOrderRequest): Promise<Order> | Observable<Order> | Order;

  getOrders(request: Empty): Promise<OrderList> | Observable<OrderList> | OrderList;

  getOrder(request: GetOrderRequest): Promise<Order> | Observable<Order> | Order;

  updateOrder(request: UpdateOrderRequest): Promise<Order> | Observable<Order> | Order;

  deleteOrder(request: DeleteOrderRequest): Promise<Empty> | Observable<Empty> | Empty;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "getOrders", "getOrder", "updateOrder", "deleteOrder"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
